# Generated by Django 2.2.7 on 2019-11-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_team', models.BooleanField(default=False)),
                ('chest_number', models.IntegerField(null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('schedule', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Events')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Events')),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.EventParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=60)),
                ('expiry', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.User')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.User')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmis_admin.Stages'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Events'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.Team'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitmis_admin.User'),
        ),
        migrations.AddConstraint(
            model_name='winners',
            constraint=models.UniqueConstraint(fields=('event', 'event_participant'), name='event_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='judges',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='event_user_unique'),
        ),
    ]
